"""added document_url in Documents table

Revision ID: 096fa2e4712e
Revises: 95e3fbb16dde
Create Date: 2026-06-16 18:08:32.165748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096fa2e4712e'
down_revision: Union[str, Sequence[str], None] = '95e3fbb16dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_url', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_url')
    # ### end Alembic commands ###
